import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import React, { useCallback, useMemo, useState } from 'react';
import {
    ActivityIndicator,
    ImageBackground,
    Platform,
    Text as RNText,
    ScrollView,
    StyleSheet,
    TouchableOpacity,
    useWindowDimensions,
    View,
} from 'react-native';
// @ts-ignore - react-native-chart-kit doesn't have TypeScript definitions
import { BarChart, LineChart, PieChart } from 'react-native-chart-kit';

import { API_BASE_URL } from '../../src/config/constants';

type ReportsTab = 'overview' | 'charts' | 'audit';

type RegistryRow = { isActive?: boolean };

type AuditLogItem = {
  id: string;
  action: string;
  actor: string;
  time: string;
  severity: 'info' | 'warning' | 'success';
};

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

const formatPercent = (value: number) => `${Math.round(value)}%`;

const safeParseJson = (rawText: string) => {
  try {
    return rawText ? JSON.parse(rawText) : null;
  } catch {
    return null;
  }
};

async function fetchRegistryRows(endpoint: string): Promise<RegistryRow[]> {
  const res = await fetch(`${API_BASE_URL}${endpoint}`, { headers: { Accept: 'application/json' } });
  const raw = await res.text();
  const json = safeParseJson(raw);

  if (!res.ok || !json?.success) {
    throw new Error(json?.message || `HTTP ${res.status} while loading ${endpoint}`);
  }

  return Array.isArray(json.data) ? json.data : [];
}

function toCsv(rows: string[][]) {
  return rows
    .map((r) => r.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\n');
}

function downloadCsvWeb(filename: string, csv: string) {
  if (Platform.OS !== 'web') return;

  const doc = (globalThis as any).document;
  const URL_ = (globalThis as any).URL;
  const Blob_ = (globalThis as any).Blob;
  if (!doc || !URL_ || !Blob_) return;

  const blob = new Blob_([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL_.createObjectURL(blob);
  const link = doc.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  doc.body.appendChild(link);
  link.click();
  doc.body.removeChild(link);
  URL_.revokeObjectURL(url);
}

async function exportPdf({
  title,
  subtitle,
  blocks,
}: {
  title: string;
  subtitle: string;
  blocks: Array<{ k: string; v: string }>;
}) {
  const html = `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial; padding: 24px; }
        h1 { margin: 0 0 6px 0; font-size: 22px; }
        .sub { color: #666; margin: 0 0 18px 0; }
        .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }
        .card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
        .k { color: #6b7280; font-size: 12px; margin-bottom: 6px; }
        .v { font-size: 18px; font-weight: 700; }
        .footer { margin-top: 18px; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p class="sub">${subtitle}</p>
      <div class="grid">
        ${blocks
          .map((b) => `<div class="card"><div class="k">${b.k}</div><div class="v">${b.v}</div></div>`)
          .join('')}
      </div>
      <div class="footer">Generated by MediVault</div>
    </body>
  </html>`;

  if (Platform.OS !== 'web') {
    const file = await Print.printToFileAsync({ html });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(file.uri);
    }
    return;
  }

  await Print.printAsync({ html });
}

export default function AdminReports() {
  const { width } = useWindowDimensions();
  const isNarrow = width < 640;
  const pagePadding = clamp(Math.round(width * 0.04), 14, 22);

  const [activeTab, setActiveTab] = useState<ReportsTab>('overview');
  const [isLoading, setIsLoading] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  const [totalPatients, setTotalPatients] = useState(0);
  const [activePatients, setActivePatients] = useState(0);
  const [totalDoctors, setTotalDoctors] = useState(0);
  const [activeDoctors, setActiveDoctors] = useState(0);

  // Displayed like the screenshot; wire to DB when appointments endpoint exists.
  const [appointmentsByStatus] = useState({
    completed: 5,
    confirmed: 3,
    pending: 1,
    cancelled: 0,
  });

  const refresh = useCallback(async () => {
    setIsLoading(true);
    setLoadError(null);

    try {
      const [patientsRows, doctorsRows] = await Promise.all([
        fetchRegistryRows('/patients/registry'),
        fetchRegistryRows('/doctors/registry'),
      ]);

      setTotalPatients(patientsRows.length);
      setActivePatients(patientsRows.filter((p) => Boolean(p.isActive)).length);

      setTotalDoctors(doctorsRows.length);
      setActiveDoctors(doctorsRows.filter((d) => Boolean(d.isActive)).length);
    } catch (e: any) {
      setLoadError(String(e?.message || e));
    } finally {
      setIsLoading(false);
    }
  }, []);

  React.useEffect(() => {
    refresh();
  }, [refresh]);

  const totalAppointments =
    appointmentsByStatus.completed +
    appointmentsByStatus.confirmed +
    appointmentsByStatus.pending +
    appointmentsByStatus.cancelled;

  const completionRate = totalAppointments > 0 ? (appointmentsByStatus.completed / totalAppointments) * 100 : 0;

  const kpis = useMemo(
    () => [
      { label: 'Total Patients', value: String(totalPatients), sub: `${activePatients} active`, icon: 'people' as const },
      { label: 'Medical Staff', value: String(totalDoctors), sub: 'Active doctors', icon: 'medkit' as const },
      {
        label: 'Total Appointments',
        value: String(totalAppointments),
        sub: `${appointmentsByStatus.pending} pending`,
        icon: 'calendar' as const,
      },
      {
        label: 'Completion Rate',
        value: formatPercent(completionRate),
        sub: `${appointmentsByStatus.completed} completed`,
        icon: 'checkmark-done' as const,
      },
    ],
    [activePatients, appointmentsByStatus.completed, appointmentsByStatus.pending, completionRate, totalAppointments, totalDoctors, totalPatients]
  );

  const chartWidth = clamp(width - pagePadding * 2 - 4, 320, 920);

  const pieData = useMemo(
    () =>
      [
        { name: 'Completed', value: appointmentsByStatus.completed, color: '#10B981' },
        { name: 'Confirmed', value: appointmentsByStatus.confirmed, color: '#3B82F6' },
        { name: 'Pending', value: appointmentsByStatus.pending, color: '#F59E0B' },
        { name: 'Cancelled', value: appointmentsByStatus.cancelled, color: '#EF4444' },
      ].filter((x) => x.value > 0 || x.name === 'Cancelled'),
    [appointmentsByStatus]
  );

  const systemActivity = useMemo(
    () => [
      { label: 'Completed Appointments', value: appointmentsByStatus.completed, color: '#10B981' },
      { label: 'Confirmed Appointments', value: appointmentsByStatus.confirmed, color: '#3B82F6' },
      { label: 'Pending Appointments', value: appointmentsByStatus.pending, color: '#F59E0B' },
      { label: 'Cancelled Appointments', value: appointmentsByStatus.cancelled, color: '#EF4444' },
    ],
    [appointmentsByStatus]
  );

  const trends = useMemo(() => {
    const labels = Array.from({ length: 14 }, (_, i) => {
      if (i === 0) return 'Dec 19';
      if (i === 6) return 'Dec 25';
      if (i === 13) return 'Jan 01';
      return '';
    });
    const data = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 9];
    return { labels, data };
  }, []);

  const workload = useMemo(
    () => ({
      labels: ['Dr. Nimal', 'Dr. Alpha', 'Dr. Kumara'],
      data: [5, 2, 2],
    }),
    []
  );

  const auditLogs: AuditLogItem[] = useMemo(
    () => [
      { id: '1', action: 'User login', actor: 'System Administrator', time: '10 mins ago', severity: 'success' },
      { id: '2', action: 'Exported Doctors CSV', actor: 'System Administrator', time: '35 mins ago', severity: 'info' },
      { id: '3', action: 'Updated user status', actor: 'System Administrator', time: '1 hour ago', severity: 'warning' },
      { id: '4', action: 'Generated report', actor: 'System Administrator', time: '2 hours ago', severity: 'info' },
    ],
    []
  );

  const exportCsv = useCallback(() => {
    const rows: string[][] = [
      ['Metric', 'Value'],
      ['Total Patients', String(totalPatients)],
      ['Active Patients', String(activePatients)],
      ['Medical Staff (Doctors)', String(totalDoctors)],
      ['Active Doctors', String(activeDoctors)],
      ['Total Appointments', String(totalAppointments)],
      ['Completed', String(appointmentsByStatus.completed)],
      ['Confirmed', String(appointmentsByStatus.confirmed)],
      ['Pending', String(appointmentsByStatus.pending)],
      ['Cancelled', String(appointmentsByStatus.cancelled)],
      ['Completion Rate', formatPercent(completionRate)],
    ];

    const csv = toCsv(rows);
    downloadCsvWeb('reports-overview.csv', csv);
  }, [activeDoctors, activePatients, appointmentsByStatus, completionRate, totalAppointments, totalDoctors, totalPatients]);

  const exportPdfHandler = useCallback(async () => {
    const blocks = [
      { k: 'Total Patients', v: String(totalPatients) },
      { k: 'Active Patients', v: String(activePatients) },
      { k: 'Medical Staff (Doctors)', v: String(totalDoctors) },
      { k: 'Active Doctors', v: String(activeDoctors) },
      { k: 'Total Appointments', v: String(totalAppointments) },
      { k: 'Completion Rate', v: formatPercent(completionRate) },
    ];

    await exportPdf({
      title: 'Reports & Analytics',
      subtitle: 'Comprehensive medical system analytics and audit logs',
      blocks,
    });
  }, [activeDoctors, activePatients, completionRate, totalAppointments, totalDoctors, totalPatients]);

  const chartConfig = useMemo(
    () => ({
      backgroundColor: '#ffffff',
      backgroundGradientFrom: '#ffffff',
      backgroundGradientTo: '#ffffff',
      decimalPlaces: 0,
      color: (opacity = 1) => `rgba(16, 185, 129, ${opacity})`,
      labelColor: (opacity = 1) => `rgba(17, 24, 39, ${opacity})`,
      propsForDots: { r: '3' },
      propsForLabels: { fontSize: 10 },
      style: { borderRadius: 12 },
    }),
    []
  );

  return (
    <View style={styles.container}>
      <ImageBackground
        source={require('../../assets/images/Background-image.jpg')}
        style={styles.background}
        resizeMode="cover"
      />
      <ScrollView style={styles.page} contentContainerStyle={{ padding: pagePadding }} showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <View style={styles.headerTextWrap}>
            <View style={styles.headerTitleRow}>
              <Ionicons name="stats-chart" size={22} color="#0891B2" />
              <RNText style={styles.title}>Reports & Analytics</RNText>
            </View>
            <RNText style={styles.subtitle}>Comprehensive medical system analytics and audit logs</RNText>
          </View>

          <View style={styles.headerActions}>
            <TouchableOpacity style={styles.actionButton} onPress={refresh}>
              <Ionicons name="refresh" size={18} color="#111827" />
              <RNText style={styles.actionButtonText}>Refresh</RNText>
            </TouchableOpacity>

            <TouchableOpacity style={styles.actionButton} onPress={exportCsv}>
              <MaterialCommunityIcons name="download" size={18} color="#111827" />
              <RNText style={styles.actionButtonText}>Export CSV</RNText>
            </TouchableOpacity>

            <TouchableOpacity style={[styles.actionButton, styles.actionButtonPrimary]} onPress={exportPdfHandler}>
              <MaterialCommunityIcons name="file-pdf-box" size={18} color="#fff" />
              <RNText style={[styles.actionButtonText, styles.actionButtonTextPrimary]}>Export PDF</RNText>
            </TouchableOpacity>
          </View>
        </View>

        <View style={styles.tabs}>
          <TouchableOpacity style={[styles.tab, activeTab === 'overview' && styles.tabActive]} onPress={() => setActiveTab('overview')}>
            <Ionicons name="bar-chart" size={16} color={activeTab === 'overview' ? '#111827' : '#6B7280'} />
            <RNText style={[styles.tabText, activeTab === 'overview' && styles.tabTextActive]}>Overview</RNText>
          </TouchableOpacity>

          <TouchableOpacity style={[styles.tab, activeTab === 'charts' && styles.tabActive]} onPress={() => setActiveTab('charts')}>
            <Ionicons name="trending-up" size={16} color={activeTab === 'charts' ? '#111827' : '#6B7280'} />
            <RNText style={[styles.tabText, activeTab === 'charts' && styles.tabTextActive]}>Charts & Trends</RNText>
          </TouchableOpacity>

          <TouchableOpacity style={[styles.tab, activeTab === 'audit' && styles.tabActive]} onPress={() => setActiveTab('audit')}>
            <Ionicons name="shield-checkmark" size={16} color={activeTab === 'audit' ? '#111827' : '#6B7280'} />
            <RNText style={[styles.tabText, activeTab === 'audit' && styles.tabTextActive]}>Audit Logs</RNText>
          </TouchableOpacity>
        </View>

        {loadError ? (
          <View style={styles.errorCard}>
            <Ionicons name="alert-circle" size={18} color="#B91C1C" />
            <RNText style={styles.errorText}>{loadError}</RNText>
          </View>
        ) : null}

        {isLoading ? (
          <View style={styles.loadingRow}>
            <ActivityIndicator />
            <RNText style={styles.loadingText}>Loading analytics…</RNText>
          </View>
        ) : null}

        <View style={styles.kpiRow}>
          {kpis.map((kpi) => (
            <View key={kpi.label} style={[styles.kpiCard, { width: isNarrow ? '100%' : '23.5%' }]}>
              <View style={styles.kpiHeader}>
                <RNText style={styles.kpiLabel}>{kpi.label}</RNText>
                <View style={styles.kpiIcon}>
                  <Ionicons name={kpi.icon} size={16} color="#6B7280" />
                </View>
              </View>
              <RNText style={styles.kpiValue}>{kpi.value}</RNText>
              <RNText style={styles.kpiSub}>{kpi.sub}</RNText>
            </View>
          ))}
        </View>

        {activeTab === 'overview' ? (
          <View style={styles.grid2}>
            <View style={[styles.card, { width: isNarrow ? '100%' : '49.2%' }]}>
              <RNText style={styles.cardTitle}>Appointment Status Distribution</RNText>
              <RNText style={styles.cardSub}>Current breakdown of all appointments by status</RNText>

              <View style={{ paddingTop: 10 }}>
                <RNText style={styles.pieCenterText}>Completed: {formatPercent(completionRate)}</RNText>
                <PieChart
                  data={pieData.map((p) => ({
                    name: p.name,
                    population: p.value,
                    color: p.color,
                    legendFontColor: '#111827',
                    legendFontSize: 12,
                  }))}
                  width={chartWidth}
                  height={220}
                  accessor="population"
                  backgroundColor="transparent"
                  paddingLeft="14"
                  chartConfig={chartConfig}
                  hasLegend={false}
                />

                <View style={styles.pieLegendRow}>
                  {systemActivity.map((item) => (
                    <View key={item.label} style={styles.legendItem}>
                      <View style={[styles.legendDot, { backgroundColor: item.color }]} />
                      <RNText style={styles.legendText}>
                        {item.label.split(' ')[0]}: {formatPercent(totalAppointments ? (item.value / totalAppointments) * 100 : 0)}
                      </RNText>
                    </View>
                  ))}
                </View>
              </View>
            </View>

            <View style={[styles.card, { width: isNarrow ? '100%' : '49.2%' }]}>
              <RNText style={styles.cardTitle}>System Activity Summary</RNText>
              <RNText style={styles.cardSub}>Real-time system statistics</RNText>

              <View style={{ marginTop: 12 }}>
                {systemActivity.map((row) => (
                  <View key={row.label} style={styles.activityRow}>
                    <View style={styles.activityLeft}>
                      <View style={[styles.activityDot, { backgroundColor: row.color }]} />
                      <RNText style={styles.activityLabel}>{row.label}</RNText>
                    </View>
                    <View style={[styles.badge, { backgroundColor: row.color }]}>
                      <RNText style={styles.badgeText}>{row.value}</RNText>
                    </View>
                  </View>
                ))}
              </View>
            </View>
          </View>
        ) : null}

        {activeTab === 'charts' ? (
          <View style={styles.grid2}>
            <View style={[styles.card, { width: '100%' }]}>
              <View style={styles.cardTitleRow}>
                <Ionicons name="trending-up" size={18} color="#111827" />
                <RNText style={styles.cardTitle}>Appointment Trends (Last 14 Days)</RNText>
              </View>
              <RNText style={styles.cardSub}>Daily appointment creation over the past two weeks</RNText>

              <LineChart
                data={{ labels: trends.labels, datasets: [{ data: trends.data }] }}
                width={chartWidth}
                height={240}
                chartConfig={{ ...chartConfig, color: (opacity = 1) => `rgba(14, 165, 233, ${opacity})` }}
                bezier
                withInnerLines
                style={{ marginTop: 14, borderRadius: 12 }}
              />
            </View>

            <View style={[styles.card, { width: '100%' }]}>
              <View style={styles.cardTitleRow}>
                <Ionicons name="medkit" size={18} color="#111827" />
                <RNText style={styles.cardTitle}>Doctor Workload Distribution</RNText>
              </View>
              <RNText style={styles.cardSub}>Top doctors by total appointments</RNText>

              <BarChart
                data={{ labels: workload.labels, datasets: [{ data: workload.data }] }}
                width={chartWidth}
                height={260}
                yAxisLabel={''}
                yAxisSuffix={''}
                fromZero
                showValuesOnTopOfBars
                chartConfig={{
                  ...chartConfig,
                  color: (opacity = 1) => `rgba(16, 185, 129, ${opacity})`,
                  fillShadowGradient: '#10B981',
                  fillShadowGradientOpacity: 1,
                }}
                style={{ marginTop: 14, borderRadius: 12 }}
              />
              <View style={styles.chartLegendCenter}>
                <View style={styles.legendItem}>
                  <View style={[styles.legendDot, { backgroundColor: '#10B981' }]} />
                  <RNText style={styles.legendText}>Total Appointments</RNText>
                </View>
              </View>
            </View>
          </View>
        ) : null}

        {activeTab === 'audit' ? (
          <View style={styles.card}>
            <RNText style={styles.cardTitle}>Audit Logs</RNText>
            <RNText style={styles.cardSub}>Recent administrative actions and system events</RNText>

            <View style={{ marginTop: 12 }}>
              {auditLogs.map((log) => (
                <View key={log.id} style={styles.auditRow}>
                  <View style={styles.auditLeft}>
                    <View
                      style={[
                        styles.auditDot,
                        log.severity === 'success'
                          ? { backgroundColor: '#10B981' }
                          : log.severity === 'warning'
                            ? { backgroundColor: '#F59E0B' }
                            : { backgroundColor: '#3B82F6' },
                      ]}
                    />
                    <View>
                      <RNText style={styles.auditAction}>{log.action}</RNText>
                      <RNText style={styles.auditMeta}>
                        {log.actor} • {log.time}
                      </RNText>
                    </View>
                  </View>
                  <Ionicons name="chevron-forward" size={18} color="#9CA3AF" />
                </View>
              ))}
            </View>
          </View>
        ) : null}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  background: { ...StyleSheet.absoluteFillObject },
  page: { flex: 1 },

  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 14,
  },
  headerTextWrap: { flexShrink: 1, minWidth: 240 },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 4 },
  title: { fontSize: 28, fontWeight: '800', color: '#111827' },
  subtitle: { color: '#6B7280', fontSize: 13 },

  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  actionButtonPrimary: {
    backgroundColor: '#0891B2',
    borderColor: '#0891B2',
  },
  actionButtonText: { fontSize: 13, fontWeight: '700', color: '#111827' },
  actionButtonTextPrimary: { color: '#ffffff' },

  tabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#EEF2F7',
    padding: 6,
    borderRadius: 12,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  tabActive: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#E5E7EB' },
  tabText: { fontSize: 13, fontWeight: '700', color: '#6B7280' },
  tabTextActive: { color: '#111827' },

  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    marginBottom: 12,
  },
  errorText: { color: '#7F1D1D', flex: 1, fontSize: 12 },

  loadingRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  loadingText: { color: '#6B7280', fontSize: 12 },

  kpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  kpiCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    minWidth: 220,
    flexGrow: 1,
  },
  kpiHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  kpiLabel: { color: '#111827', fontWeight: '700', fontSize: 13 },
  kpiIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiValue: { fontSize: 28, fontWeight: '800', color: '#111827', marginTop: 10 },
  kpiSub: { marginTop: 4, color: '#6B7280', fontSize: 12, fontWeight: '600' },

  grid2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'space-between',
  },

  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 16,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardTitle: { fontSize: 18, fontWeight: '800', color: '#111827' },
  cardSub: { marginTop: 6, color: '#6B7280', fontSize: 12 },

  pieCenterText: { textAlign: 'center', color: '#10B981', fontWeight: '800', marginBottom: 8 },
  pieLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    marginTop: 8,
  },

  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 10, height: 10, borderRadius: 99 },
  legendText: { color: '#374151', fontWeight: '700', fontSize: 12 },

  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  activityLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flexShrink: 1 },
  activityDot: { width: 10, height: 10, borderRadius: 99 },
  activityLabel: { color: '#111827', fontWeight: '700', fontSize: 13, flexShrink: 1 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  badgeText: { color: '#fff', fontWeight: '800', fontSize: 12 },

  chartLegendCenter: { alignItems: 'center', marginTop: 10 },

  auditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  auditLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flexShrink: 1 },
  auditDot: { width: 10, height: 10, borderRadius: 99 },
  auditAction: { color: '#111827', fontWeight: '800', fontSize: 13 },
  auditMeta: { color: '#6B7280', fontSize: 12, marginTop: 2 },
});
